### ISSUE TITLE
1.20.4 scoreboard

### ISSUE THREAD

**Issue by Maracajudo** [jewtvet/boathud-f1#1]
When attempting to join a race in boatlabs 1.20.4 running through modrinth with default settings, the game crashes with a log message of
"[18:41:18] [Render thread/ERROR]:
 Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_266 net.minecraft.class_269.method_1165(java.lang.String)'
	at jewtvet.boathud_f1.ScoreboardAccessor.getScoreboardLines(ScoreboardAccessor.java:25) ~[boathud-f1-1.0.1.jar:?]
	at net.minecraft.class_329.handler$zza000$boathud_f1$onRenderScoreboard(class_329.java:1536) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1757(class_329.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_329.method_1753(class_329.java:379) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:912) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1327) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.11.jar:?"
I have tried this in the 1.21 release version without error, and 1.20.4 beta and release with error, but have not tested any further. this error also wasn't present 2 days ago when I tried it.

**Comment by Timocst1** [comment]
i have the same issues
